POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Ayrton Senna's Legacy",
  "postType": "post",
  "slug": "historic-formula-one",
  "status": "draft",
  "content": "Fearless. Visionary. Ruthless. Spiritual. Rainmaster. Maverick. Intense. Elegant. Obsessive. Transcendent.",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2025-08-10T22:18:49+0000",
  "tags": ["champion", "mclaren"],
  "metaOptions": [
    {
      "key": "testKey",
      "value": 20
    }
  ]
}