POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Leonardo",
  "lastName": "Benjamin",
  "email": "lenny@nimira.com",
  "password": "ThisPassword@123",
  "isAuth": true
}